#!/bin/bash

#creates GEMFILE
echo -e "source 'https://rubygems.org'\n
gem 'rspec'" > Gemfile
printf "Gemfile created\n"

#executes GEMFILE
bundle install --path .bundle
printf "bundle installed\n"

#make filesystem
mkdir spec
mkdir lib
printf "folders spec and lib created\n"

#message
printf "DONE\n"
printf "run 'bundle exec rspec' to test\n"
